CREATE TABLE baby (
    id int NOT NULL AUTO_INCREMENT,
    league_num int not null,
    week_num int not null,
    home varchar(3) not null,
    away varchar(3) not null,
    home_odd float not null,
    away_odd float not null,
    draw_odd float not null,
    home_draw_odd float not null,
    away_draw_odd float not null,
    any_body_odd float not null,
    gg_odd float not null,
    ng_odd float not null,
    over_2 float not null,
    under_2 float not null,
    result varchar(20) not null,
    home_form varchar(20) not null,
    away_form varchar(20) not null,
    home_pos int not null,
    away_pos int not null,
    home_point int not null,
    away_point int not null,
    PRIMARY KEY(id)
);
